name: test_month_days

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Ubuntu 環境で実行
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # リポジトリをクローン

    - name: Check if the file exists
      run: ls -l ./kadai_1  # kadai1 ディレクトリ内のファイルをリスト表示して存在を確認

    - name: Grant execute permissions
      run: chmod +x ./kadai_1/month_days.bash  # 実行権限を付与

    - name: Run tests
      run: |
        bash -xv ./kadai_1/month_days.bash  # テストを実行するコマンド

